import = [
    "~/.config/alacritty/themes/theme.toml"
]

[font]
normal = { family  = "MonaspiceNe Nerd Font Mono", style = "Bold" }
#normal = { family  = "Monaspace Neon", style = "Regular" }

[window]
opacity = 0.75
decorations = "none"
startup_mode = "Maximized"

[colors.primary]
# Override Campbell's bg color for a darker grey
background = '#070707'

[keyboard]
bindings = [
    # Allow font increase on fr-ch
   { key = "1", mods = "Control", action = "IncreaseFontSize" }
]
