# _                        
#| |_ _ __ ___  _   ___  __
#| __| '_ ` _ \| | | \ \/ /
#| |_| | | | | | |_| |>  < 
# \__|_| |_| |_|\__,_/_/\_\


# Set prefix to Ctrl+J
set -g prefix C-g
bind-key C-g send-prefix

#Enable mouse
set -g mouse on

# Remove delay when pressing Escape
set -sg escape-time 20

# Start windows at 1
set -g base-index 1
# Prevent index gaps
set-option -g renumber-windows on

# Reload the config with r (May become deprecated)
unbind r
bind r source-file ~/.tmux.conf

# Split the window with more comfortable keybind (for fr-ch)
bind-key é split-window -h
bind-key à split-window -v

# Toggle status bar
bind-key s set-option status

# Move between panes like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key l select-pane -R
bind-key k select-pane -U

set -g status-style bg="colour235",fg="white"
set-option -g status-justify 'centre'

set -g status-left '#[bg=colour81]#[fg=colour235] #{?client_prefix,#[fg=magenta]P#[fg=colour235],N}|#{?pane_in_mode,#[fg=colour106]C#[fg=colour235],I} '
set -g status-right '#[bg=colour81]#[fg=colour235] #S:#I.#P '

set -g window-status-format " #I:#W#F "
set -g window-status-current-format "#[bg=white fg=black,bold] #I:#W#F "
set-window-option -g window-status-separator "|"
