export EDITOR=/bin/nvim
export PAGER="bat"
export MANPAGER=$PAGER
export BAT_THEME="Visual Studio Dark+"
export TERMINAL=st
export LOCKER="i3lock -ne -i ""$HOME""/images/lockscreen.png"

export PATH="$PATH:""$HOME""/.local/bin"
# Add all directories in `~/.local/bin` to $PATH
export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"
export PATH="$PATH:$(find ~/.local/bin -type l | paste -sd ':' -)"

export AUTO_NOTIFY_THRESHOLD=30
AUTO_NOTIFY_IGNORE+=("docker" "ytfzf" "btop" "bat" "lf" "paru" "pacman" "bashmount" "qalc")
