export EDITOR=/bin/nvim
export PAGER="bat"
export MANPAGER=$PAGER
export BAT_THEME="Visual Studio Dark+"
export TERMINAL=st
export LOCKER="i3lock -ne -i ""$HOME""/images/lockscreen.png"

if [[ ":$PATH:" != *":$HOME/.local/bin"* ]]; then
    export PATH="$PATH:""$HOME""/.local/bin"
fi

export AUTO_NOTIFY_THRESHOLD=30
AUTO_NOTIFY_IGNORE+=("docker" "ytfzf" "btop" "bat" "lf" "paru" "pacman" "bashmount" "qalc")
