export PATH="$PATH":"$HOME"/.local/bin
export EDITOR=/bin/nvim
export MANPAGER="bat"
export BAT_THEME="Visual Studio Dark+"
export TERMINAL=st
export LOCKER="i3lock -ne -i ""$HOME""/images/lockscreen.png"

if [[ ":$PATH:" != *":$HOME/.local/bin"* ]]; then
    export PATH="$PATH:""$HOME""/.local/bin"
fi

export AUTO_NOTIFY_THRESHOLD=30
