# Custom theme

if patched_font_in_use; then
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=""
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN=""
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=""
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=""
else
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="◀"
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN="❮"
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="▶"
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="❯"
fi

TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR:-'235'}
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR:-'255'}

TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD}
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_LEFT_BOLD}

# See man tmux.conf for additional formatting options for the status line.
# The `format regular` and `format inverse` functions are provided as conveniences

if [ -z $TMUX_POWERLINE_WINDOW_STATUS_CURRENT ]; then
	TMUX_POWERLINE_WINDOW_STATUS_CURRENT=(
		"#[$(format inverse)]"
		"$TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR"
		" #I#F "
		"$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN"
		" #W "
		"#[$(format regular)]"
		"$TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR"
	)
fi

if [ -z $TMUX_POWERLINE_WINDOW_STATUS_STYLE ]; then
	TMUX_POWERLINE_WINDOW_STATUS_STYLE=(
		"$(format regular)"
	)
fi

if [ -z $TMUX_POWERLINE_WINDOW_STATUS_FORMAT ]; then
	TMUX_POWERLINE_WINDOW_STATUS_FORMAT=(
		"#[$(format regular)]"
		"  #I#{?window_flags,#F, } "
		"$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN"
		" #W "
	)
fi

if [ -z $TMUX_POWERLINE_LEFT_STATUS_SEGMENTS ]; then
	if [[ USH_TPL_TH_ALT -eq 1 ]]; then
		TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
			"tmux_session_info 81 0 ${TMUX_POWERLINE_SEPARATOR_RIGHT_THIN}"
			"modes 81 0"
			"text 218 0 ${TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD} 218 0 right_disable separator_disable"
			"hostname 218 0"
		)
	else
		TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
			"tmux_session_info 21 255 ${TMUX_POWERLINE_SEPARATOR_RIGHT_THIN}"
			"modes 21 255"
			"text 27 0"
			"hostname 33 0"
		)
	fi
fi

if [ -z $TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS ]; then
	TMUX_POWcRLINE_RIGHT_STATUS_SEGMENTS=(
		"pwd 33 0"
		"weather 27 0"
		"date 21 255"
		"time 21 255 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}"

		#"pwd 218 0"
		#"weather 218 0 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}"
		#"date 81 16"
		#"time 81 16 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}"
	)
	if [[ USH_TPL_TH_ALT -eq 1 ]]; then
		TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
			"pwd 218 0"
			"weather 218 0 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}"
			"date 81 16"
			"time 81 16 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}"
		)
	else
		TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
			"pwd 33 0"
			"weather 27 0"
			"date 21 255"
			"time 21 255 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}"
		)
	fi
fi
