font=Monaspace Neon NF:size=12

initial-window-size-chars=150x45
initial-window-mode=maximized
# bold-text-in-bright=no

[bell]
visual=yes

[colors-dark]
alpha=0.8
# background=242424
# foreground=ffffff
# flash=7f7f00
# flash-alpha=0.5

## Normal/regular colors (color palette 0-7)
regular0=000000  # black
regular1=c40000  # red
regular2=00c400  # green
regular3=e3c401  # yellow
regular4=4549de  # blue
regular5=c400c4  # magenta
regular6=00c4c4  # cyan
regular7=c4c4c4  # white

## Bright colors (color palette 8-15)
bright0=616161   # bright black
bright1=ff4d51   # bright red
bright2=35d450   # bright green
bright3=ffff00   # bright yellow
bright4=5dc5f8   # bright blue
bright5=feabf2   # bright magenta
bright6=00ffff   # bright cyan
bright7=ffffff   # bright white

[key-bindings]
font-increase=Control+plus Control+equal Control+KP_Add Control+Shift+Page_Up
font-decrease=Control+minus Control+KP_Subtract Control+Shift+Page_Down
font-reset=Control+0 Control+KP_0 Control+Shift+Home

# vim: ft=dosini
